Allow for parsing of sequential ranges
elliottneilclark/rs-poker pull request #91
Opened 2024-02-19 20:55 UTC by JohannesKlauss

Currently the library cannot parse a sequential range where the rank of the first card is constant, something like `A5-A2s`. This addition allows to parse that.

If I should change anything, please let me know 🙂

2024-02-20 17:33 UTC, elliottneilclark requested changes

2024-02-20 17:33 UTC, elliottneilclark commented on src/holdem/parse.rs
> +        );
Please add a test showing that each hand satisfies the invariants.

- Every hand has an Ace in it.
- The other card is between 9 and 5
- Both cards are the same suit

2024-02-20 17:33 UTC, elliottneilclark commented on src/holdem/parse.rs
> +    Sequential(Value, u8),
I  think `StaticWithRange` or `StaticRange` are better names. These aren't hands where the cards are sequential.

2024-02-20 17:34 UTC, elliottneilclark commented
I really like this feature. Thank you other than naming and a little extra testing this looks good.

2024-02-21 09:32 UTC, JohannesKlauss commented
> I really like this feature. Thank you other than naming and a little extra testing this looks good.

I added the requested changes. Can you tell me what code format analyzer you are using? Doesn't state it in the CLI output.

2024-02-21 15:37 UTC, elliottneilclark approved these changes
<img src="https://media1.giphy.com/media/PoImMjCPa8QaiBWJd0/giphy.gif"/>

2024-02-21 15:42 UTC, elliottneilclark commented
> Can you tell me what code format analyzer you are using?

For the testing, we run the equivalent of the following:

```
cargo fmt --all
cargo clippy --all-targets --all
cargo test --all --all-targets
cargo audit
```

2024-02-21 15:45 UTC, merged

2024-02-25 10:50 UTC, JohannesKlauss commented
@elliottneilclark Would it be possible to publish a new release, so I can use that feature 🙂 ?

2024-02-27 17:55 UTC, elliottneilclark commented
@JohannesKlauss `v3.0.0-beta.8` is released.